# %player%는 접속한 플레이어의 이름으로 자동 변경됩니다.
# & 기호로 색상 코드를 사용할 수 있습니다. (예: &a, &b, &c...)
# 줄바꿈 (\n) 사용이 가능합니다.

  # 콘솔 로그, 인게임 안내 등에 사용되는 서버 이름입니다. 기본값은 EC입니다.
server-name: "서버"
  # 차단된 플레이어에게 문의할 곳은 안내해주거나, 기타 서버 문의 주소로 사용됩니다.
server-community: "https://dev.stopzero.site"

  # 권한이 부족할 때 출력될 메세지입니다.
permission-message: "이 명령어를 사용할 권한이 없습니다."

  # 처벌 관련 설정입니다.
punishments:
    # /추방 명령어 사용 시 전체채팅방에 표시될 메세지입니다.
    # %player% -> 추방된 플레이어의 이름
    # %sender$ -> 추방한 플레이어의 이름
    # %reason% -> 추방 사유 로 치환됩니다.
  kick-broadcast-message: ""

    # /밴 명령어 사용 시 전체채팅방에 표시될 메세지입니다.
    # %player% -> 차단된 플레이어의 이름
    # %sender$ -> 차단한 플레이어의 이름
    # %reason% -> 밴 사유 로 치환됩니다.
  ban-broadcast-message: ""

    # /임시밴(tempban) 명령어 사용 시 전체채팅방에 표시될 메세지입니다.
    # 설정한 메세지 뒤에 *만료: <만료기한>* 문구가 자동으로 추가됩니다.
    # %player% -> 차단된 플레이어의 이름
    # %sender$ -> 차단한 플레이어의 이름
    # %reason% -> 밴 사유 로 치환됩니다.
  tempban-broadcast-message: ""

    # /밴해제 명령어 사용 시 전체채팅방에 표시될 메세지입니다.
    # %player% -> 밴 해제된 플레이어의 이름
    # %sender$ -> 밴 해제한 플레이어의 이름 으로 치환됩니다.
  unban-broadcast-message: ""


#플레이어 접속/퇴장 관련 설정입니다.
#log-message 항목은 콘솔에 표시될 메세지입니다.

join-quit:
  # 플레이어 접속시 메세지입니다.
  join-message: "&l[ &a+ &f&l] %player%"
  join-log-message: "%player%님이 서버에 접속하셨습니다."

  # 플레이어가 접속 했을 때 해당 유저에게 개인 메세지를 표시할지 여부입니다.
  send-private-message-on-join: false
  private-message-on-join: "%player%님 오늘도 접속해주셔서 감사합니다."


  # 플레이어가 처음 접속 했을 때의 메세지입니다.
  first-join-message: "&l[ &a+ &f&l] %player% &f님이 서버에 처음 접속하셨습니다!"
  first-join-log-message: "%player%님이 처음으로 서버에 접속하셨습니다!"

  # 플레이어가 처음 접속 했을 때 해당 유저에게 개인 메세지를 표시할지 여부입니다.
  send-private-message-on-first-join: true
  private-message-on-first-join: "%player%님 서버에 처음 접속하신 것을 환영합니다."


  # 플레이어 퇴장시 메세지입니다.
  quit-message: "&l[ &c- &f&l] %player%"
  quit-log-message: "%player%님이 서버에서 퇴장하셨습니다."
