# %player%는 접속한 플레이어의 이름으로 자동 변경됩니다.
# & 기호로 색상 코드를 사용할 수 있습니다. (예: &a, &b, &c...)
# 줄바꿈 (\n) 사용이 가능합니다.



permission-message: "이 명령어를 사용할 권한이 없습니다."


#플레이어 접속시 메세지입니다.
#log-message 항목은 콘솔에 표시될 메세지입니다.

join-message: "&l[ &a+ &f&l] %player%"
join-log-message: "%player%님이 서버에 접속하셨습니다."



#플레이어가 처음 접속 했을 때의 메세지입니다.

first-join-message: "&l[ &a+ &f&l] %player% &f님이 서버에 처음 접속하셨습니다!"
first-join-log-message: "%player%님이 처음으로 서버에 접속하셨습니다!"

send-welcome-message-on-first-join: true
private-welcome-message: "%player%님 서버에 처음 접속하신 것을 환영합니다."



#플레이어 퇴장시 메세지입니다.

quit-message: "&l[ &c- &f&l] %player%"
quit-log-message: "%player%님이 서버에서 퇴장하셨습니다."